- hosts: localhost
  pre_tasks:
    - name: Update apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
  tasks:
    - name: Install system packages
      become: true
      apt:
        name:
          - asciinema
          - curl
          - entr
          - firefox
          - fish
          - flameshot
          - fzf
          - gimp
          - git
          - jq
          - kazam
          - moreutils
          - mpv
          - ncdu
          - python3-pip
          - sqlite3
          - stow
          - tree
          - unzip
          - wget
          - zip
          # NOTE: these tend to be outdated, and could be installed from GitHub
          - bat
          - fd-find
          - git-delta
          - ripgrep
    - name: Install python3 packages
      pip:
        name:
          - Commitizen
          - radian
        extra_args: --user
    - name: Install Go
      become: true
      unarchive:
        src: "https://go.dev/dl/{{ lookup('url', 'https://go.dev/VERSION?m=text', split_lines=False) }}.linux-amd64.tar.gz"
        remote_src: true
        dest: /usr/local
      tags: go
