- hosts: localhost
  pre_tasks:
    - name: Update apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
  tasks:
    - name: Core
      include_tasks: "tasks/core.yml"
    - name: Go
      include_tasks: "tasks/go.yml"
    - name: R
      include_tasks: "tasks/r.yml"
