- name: "install"
  become: true
  ansible.builtin.apt:
    name:
      - fzf
    autoclean: true
    autoremove: true
    update_cache: true

- name: "fd"
  block:
    - name: "fd : fetch version"
      community.general.github_release:
        user: sharkdp
        repo: fd
        action: latest_release
      register: release

    - name: "fd : install (amd64)"
      become: true
      ansible.builtin.apt:
        deb: "https://github.com/sharkdp/fd/releases/download/{{ release.tag }}/fd_{{ release.tag[1:] }}_amd64.deb"
      when: ansible_architecture == "x86_64"

    - name: "fd : install (arm64)"
      become: true
      ansible.builtin.apt:
        deb: "https://github.com/sharkdp/fd/releases/download/{{ release.tag }}/fd_{{ release.tag[1:] }}_arm64.deb"
      when: ansible_architecture == "aarch64"
