- ansible.builtin.import_tasks: debian.yaml
  when: ansible_os_family == "Debian"

- name: "gopls"
  ansible.builtin.shell: /usr/local/go/bin/go install golang.org/x/tools/gopls@latest

- name: "goimports"
  ansible.builtin.shell: /usr/local/go/bin/go install golang.org/x/tools/cmd/goimports@latest
