- name: "add key"
  become: true
  ansible.builtin.apt_key:
    url: https://downloads.1password.com/linux/keys/1password.asc

- name: "add repository (amd64)"
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://downloads.1password.com/linux/debian/amd64 stable main"
    filename: "1password"
  when: ansible_architecture == "x86_64"

- name: "add debsig-verify policy"
  become: true
  ansible.builtin.shell: |
    sudo mkdir -p /etc/debsig/policies/AC2D62742012EA22/
    curl -sS https://downloads.1password.com/linux/debian/debsig/1password.pol | sudo tee /etc/debsig/policies/AC2D62742012EA22/1password.pol
    sudo mkdir -p /usr/share/debsig/keyrings/AC2D62742012EA22
    curl -sS https://downloads.1password.com/linux/keys/1password.asc | sudo gpg --dearmor --output /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg

- name: "install"
  become: true
  ansible.builtin.apt:
    name: 1password
    autoclean: true
    autoremove: true
    update_cache: true
  when: ansible_architecture == "x86_64"
