- import_tasks: debian.yaml
  when: ansible_os_family == "Debian"

- name: "vim-plug"
  shell: >
    curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

- name: "plugins"
  shell: nvim -c 'PlugInstall' -c 'TSInstall all' -c 'qa'
